{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.vampirestudios",
    "module": "VampireLib-Fabric",
    "version": "4.6.1+build.3-1.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.3+1.18"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "6.0.42"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.vampirestudios",
          "module": "artifice",
          "version": {
            "requires": "0.15.10+21w20a"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "VampireLib-Fabric-4.6.1+build.3-1.18.1.jar",
          "url": "VampireLib-Fabric-4.6.1+build.3-1.18.1.jar",
          "size": 1908084,
          "sha512": "2ae48628567e9a7755f50870a90aa02e1199981babd472da8cbcb915e30dfd8e97df9e16121b4a41ddfa6b590af575ef5ee3a518a1b3fe2f4e8b3918caab6c0a",
          "sha256": "499e9d7b9199b73902e189d16e3f26ab1d40333c5d8fdb54953a98fa9d992ad9",
          "sha1": "069849e529fed9fa545ce50c7c877d1e285805e7",
          "md5": "bb4429e6ab74370442f31e135d2381a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.3+1.18"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "6.0.42"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.vampirestudios",
          "module": "artifice",
          "version": {
            "requires": "0.15.10+21w20a"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.12.12"
          }
        },
        {
          "group": "com.terraformersmc.terraform-api",
          "module": "terraform-wood-api-v1",
          "version": {
            "requires": "2.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "VampireLib-Fabric-4.6.1+build.3-1.18.1.jar",
          "url": "VampireLib-Fabric-4.6.1+build.3-1.18.1.jar",
          "size": 1908084,
          "sha512": "2ae48628567e9a7755f50870a90aa02e1199981babd472da8cbcb915e30dfd8e97df9e16121b4a41ddfa6b590af575ef5ee3a518a1b3fe2f4e8b3918caab6c0a",
          "sha256": "499e9d7b9199b73902e189d16e3f26ab1d40333c5d8fdb54953a98fa9d992ad9",
          "sha1": "069849e529fed9fa545ce50c7c877d1e285805e7",
          "md5": "bb4429e6ab74370442f31e135d2381a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VampireLib-Fabric-4.6.1+build.3-1.18.1-sources.jar",
          "url": "VampireLib-Fabric-4.6.1+build.3-1.18.1-sources.jar",
          "size": 1503816,
          "sha512": "ce6e154608a485cabc529acc41c94ce9bc74bfef6f7f7a44e18940f86cfecd26682ac4b36e8ad482c526cd1db0259126f638c9d1979435811c80ff70a1dc12f7",
          "sha256": "f57d5eb8b5dc481772a129ee3967eec0114d3b397538fc56b99d1fb2a8286493",
          "sha1": "b2ddffac0656da0337ca2cce2fadb43924a4ebe4",
          "md5": "6214b48f0d2e2d58f9e0b1133af47c2b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VampireLib-Fabric-4.6.1+build.3-1.18.1-javadoc.jar",
          "url": "VampireLib-Fabric-4.6.1+build.3-1.18.1-javadoc.jar",
          "size": 764838,
          "sha512": "5d73433212ae7cdc5588bf6a1fa8058d3cfd8409942da3521a9be52774a36b72529dae4a9fb6ba04f8ca9da0043a28ff5fe8cfa52472685b039c94e7f3a13c17",
          "sha256": "a8f6d8ba64ed6bfd808437d974eeb3fb08f91e90aa439fda0111b2d65af07421",
          "sha1": "e59f04af1d69272634af85fbeebab55dc25f16b9",
          "md5": "ed5b257bdfcdc3ab955faca1f347f639"
        }
      ]
    }
  ]
}
