{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.vampirestudios",
    "module": "VampireLib-Fabric",
    "version": "4.6.0+build.1-1.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.3+1.18"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "6.0.42"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.vampirestudios",
          "module": "artifice",
          "version": {
            "requires": "0.15.10+21w20a"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "VampireLib-Fabric-4.6.0+build.1-1.18.1.jar",
          "url": "VampireLib-Fabric-4.6.0+build.1-1.18.1.jar",
          "size": 1906448,
          "sha512": "a761122d07ccc9aa8c793fe38d5f896d00415b276844f97e5259b33b13872afd9ca3d192d8f5a2a275cf4ab2970ccb447b2fcca6174723e7adb9a91647b5febc",
          "sha256": "4448a0066b05c56dda3bfdcf1d40ad2f93edecfde424591a9964ad3738c3750c",
          "sha1": "e009c54dcde0e46df3e1f345c625ad85a2d888a3",
          "md5": "264c4cf6fb02e7e001e2049fa84d6556"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.3+1.18"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "6.0.42"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.vampirestudios",
          "module": "artifice",
          "version": {
            "requires": "0.15.10+21w20a"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.12.12"
          }
        },
        {
          "group": "com.terraformersmc.terraform-api",
          "module": "terraform-wood-api-v1",
          "version": {
            "requires": "2.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "VampireLib-Fabric-4.6.0+build.1-1.18.1.jar",
          "url": "VampireLib-Fabric-4.6.0+build.1-1.18.1.jar",
          "size": 1906448,
          "sha512": "a761122d07ccc9aa8c793fe38d5f896d00415b276844f97e5259b33b13872afd9ca3d192d8f5a2a275cf4ab2970ccb447b2fcca6174723e7adb9a91647b5febc",
          "sha256": "4448a0066b05c56dda3bfdcf1d40ad2f93edecfde424591a9964ad3738c3750c",
          "sha1": "e009c54dcde0e46df3e1f345c625ad85a2d888a3",
          "md5": "264c4cf6fb02e7e001e2049fa84d6556"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VampireLib-Fabric-4.6.0+build.1-1.18.1-sources.jar",
          "url": "VampireLib-Fabric-4.6.0+build.1-1.18.1-sources.jar",
          "size": 1502962,
          "sha512": "34e9da564fc93839bb1b844cdebd6157ff8c58776a126379cbcc7e611012f7af83b6cf5edde0fb89d673c729b40d8ad14c9c92edd491b7e1d6e83afc6e1b3d70",
          "sha256": "e89fba27c310b4133cd8b8285dc2f2afa8c92928f1b84c7caac3e2b081b3ac8c",
          "sha1": "cf4058708c9ab35c90b5199a809585588d8ea0b3",
          "md5": "8fbbd48d4e9e76e88019788ab9e8bfcd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VampireLib-Fabric-4.6.0+build.1-1.18.1-javadoc.jar",
          "url": "VampireLib-Fabric-4.6.0+build.1-1.18.1-javadoc.jar",
          "size": 760302,
          "sha512": "abee54a2fcdf7e01d35cd6704be448db3086aee02ceede9b14da32461278a64204a8d7a2c28c82b97efe5e56499038bcff34b5ef6662adfbac1afe947cc6fee6",
          "sha256": "04df776761ce37ef426cb65acf5afffcd6c4008e2e574a9abdb57cc1ef0d5ce4",
          "sha1": "c430c1428d27da5a9afed04ac57f33711a381e87",
          "md5": "3d5743ecd87fe050772eb0c2e605a6ee"
        }
      ]
    }
  ]
}
