{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.vampirestudios",
    "module": "Randomly-Adding-Anything-Core",
    "version": "2.1.1+1.18.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "6.2.57"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "Randomly-Adding-Anything-Core-2.1.1+1.18.2.jar",
          "url": "Randomly-Adding-Anything-Core-2.1.1+1.18.2.jar",
          "size": 3950487,
          "sha512": "abd7e4d2b2d547f36875a07e81d70a459f72a8f2e7cf0491407555df87f5c7409be9f3ce818e974e066edb84f8ca0e8ef7a81bdbb2b58fb7c4905f5664801448",
          "sha256": "54610e54a8f7eb23cbb8a271debbaf0b68c1444eb2b7fb5b5a9d8063872dcc0b",
          "sha1": "1da4de6a12ccd5b50f2ee55a75657c7ef065f8aa",
          "md5": "493a67d45616810ab8316adff5928573"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "6.2.57"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.13.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.47.8+1.18.2"
          }
        },
        {
          "group": "io.github.vampirestudios",
          "module": "VampireLib-Fabric",
          "version": {
            "requires": "4.8.2+build.2-1.18.2-pre3"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "io.github.cottonmc",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "Randomly-Adding-Anything-Core-2.1.1+1.18.2.jar",
          "url": "Randomly-Adding-Anything-Core-2.1.1+1.18.2.jar",
          "size": 3950487,
          "sha512": "abd7e4d2b2d547f36875a07e81d70a459f72a8f2e7cf0491407555df87f5c7409be9f3ce818e974e066edb84f8ca0e8ef7a81bdbb2b58fb7c4905f5664801448",
          "sha256": "54610e54a8f7eb23cbb8a271debbaf0b68c1444eb2b7fb5b5a9d8063872dcc0b",
          "sha1": "1da4de6a12ccd5b50f2ee55a75657c7ef065f8aa",
          "md5": "493a67d45616810ab8316adff5928573"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Randomly-Adding-Anything-Core-2.1.1+1.18.2-sources.jar",
          "url": "Randomly-Adding-Anything-Core-2.1.1+1.18.2-sources.jar",
          "size": 1235650,
          "sha512": "8a3d6bbb8382bf5b95d9a9c2fa8bc7658918216b4c2fdc9a85734c81347ad87627c6ffbe5acdcb3ee9e64c98fc0e92624b3cb1c292a8784c78f42cfd60daa0ee",
          "sha256": "151cf14ef7da047629a92dfe98b3f56093b27469deb4c897c91f1184f0fd8f8f",
          "sha1": "d080e0809eda67557c247fc2102b2cb5c0ccee03",
          "md5": "0572c4cc31c46bcc2b3b3e3bc252f7c6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Randomly-Adding-Anything-Core-2.1.1+1.18.2-javadoc.jar",
          "url": "Randomly-Adding-Anything-Core-2.1.1+1.18.2-javadoc.jar",
          "size": 186091,
          "sha512": "584aad9bb04b961b16f685a854853ad21d299d4815df3e9cb9cf807330d5f2617d5bb6037135ae602773c292334a2776094e7124ca883b3aef67aefd19fc1d44",
          "sha256": "ef2063f02222e9996bdfce368e9d3d4c6d9140034bb41c0d31bce3f294e24ba2",
          "sha1": "f3311ea2288dc9b30ccc04faa3d8c55f76dd0d9d",
          "md5": "dd1bcfb1a7284d6ddca1e581a90b3454"
        }
      ]
    }
  ]
}
