{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.vampirestudios",
    "module": "VampireLib-Fabric",
    "version": "4.7.0+build.2-1.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.3+1.18"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "6.1.48"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.vampirestudios",
          "module": "artifice",
          "version": {
            "requires": "0.15.10+21w20a"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "VampireLib-Fabric-4.7.0+build.2-1.18.1.jar",
          "url": "VampireLib-Fabric-4.7.0+build.2-1.18.1.jar",
          "size": 1951558,
          "sha512": "23f1664aec6d678772c969f69f814e3ebc407564c2e1fa78fd3271053747fd525b9feec334b55585bd452f6506fb9cd37f93de666b7c785d7f3556920f00c545",
          "sha256": "3889e51b3c55751169e04169707d04e7f7e2f5fa72f2fb034723b6257e04d6c7",
          "sha1": "b637f18cd391ca68eb862b755053d4dce624581d",
          "md5": "2b7784c40521df13c94a70dc06ad740a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.3+1.18"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "6.1.48"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.vampirestudios",
          "module": "artifice",
          "version": {
            "requires": "0.15.10+21w20a"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.12.12"
          }
        },
        {
          "group": "com.terraformersmc.terraform-api",
          "module": "terraform-wood-api-v1",
          "version": {
            "requires": "2.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "VampireLib-Fabric-4.7.0+build.2-1.18.1.jar",
          "url": "VampireLib-Fabric-4.7.0+build.2-1.18.1.jar",
          "size": 1951558,
          "sha512": "23f1664aec6d678772c969f69f814e3ebc407564c2e1fa78fd3271053747fd525b9feec334b55585bd452f6506fb9cd37f93de666b7c785d7f3556920f00c545",
          "sha256": "3889e51b3c55751169e04169707d04e7f7e2f5fa72f2fb034723b6257e04d6c7",
          "sha1": "b637f18cd391ca68eb862b755053d4dce624581d",
          "md5": "2b7784c40521df13c94a70dc06ad740a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VampireLib-Fabric-4.7.0+build.2-1.18.1-sources.jar",
          "url": "VampireLib-Fabric-4.7.0+build.2-1.18.1-sources.jar",
          "size": 1501039,
          "sha512": "5bfb5b0c4187b37ee108650a062a88de181a7ae0138fb53d832b9bf8868b270c544583327be339c64cca86b65b4acf0b006bb780020992641013ecdfae11d819",
          "sha256": "28eeb5491460f3bb4e99f9c2db319c5c5f64fff6c4b1813466e504c2ad189057",
          "sha1": "f16df6e36b1db5f43a5ccc8cc8de2cd39711c3e9",
          "md5": "b10470be325848f873dd2a54219ea3b2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VampireLib-Fabric-4.7.0+build.2-1.18.1-javadoc.jar",
          "url": "VampireLib-Fabric-4.7.0+build.2-1.18.1-javadoc.jar",
          "size": 798566,
          "sha512": "fd8fc2185738f5b1dd9f9d8dadc8df1403b8f66f8410f9e73605c7e878db0344579ac25036fbab0f1ac82e638419273fa336735ce988b881f457933ad89c9625",
          "sha256": "57b3ab62c52909b86d8a70c14e09df6c993edfca8502a09b916ffef67a08ad46",
          "sha1": "7eeef1154a5640f3895a9805e18db6e28ca8a3ed",
          "md5": "862fce0187b75434e769f973e0f5d9f5"
        }
      ]
    }
  ]
}
